# This is a basic workflow to help you get started with Actions

name: Build Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions: write-all
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          # - StandaloneWindows # Build a Windows standalone.
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android .apk standalone app.
           - WebGL # WebGL.
        artifactsPath:
          - artifacts
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache
      - uses: actions/cache@v2
        with:
            path: Library
            key: Library-build-main-${{ matrix.targetPlatform }}
            restore-keys: Library-build-main

      # Test
      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: ${{ matrix.artifactsPath }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
            name: Test results
            path: ${{ steps.tests.outputs.artifactsPath }}

      # Build
      # Change the name to the name of the branch
      - name: Build Game
        uses: game-ci/unity-builder@v2
        env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
            targetPlatform: ${{ matrix.targetPlatform }}
            customParameters: -CompressWithLz4HC
            allowDirtyBuild: false

      - uses: actions/upload-artifact@v2
        with:
            name: main_${{ matrix.targetPlatform }}_build_${{github.run_number}}
            path: build
